### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by guiamuchastegui** [Vibration-Testing/vibrationtesting#24]
I am not being able to install vibrationtesting.
I am currently using Python 3.7, trying to install with the following commands:

pip install --user vibrationtesting 

When I perform the above command in the terminal, I receive many lines with the message:
- Requirement already satisfied: vibratinotesting in c:/......

When I try to run my code, I get the message: 
File "C:/Users/joseg/dev/ensus/ods/teste.py", line 6, in <module>
    import vibrationtesting as vt
ModuleNotFoundError: No module named 'vibrationtesting'

Can anyone help me?

**Comment by josephcslater** [comment]
Most likely you have multiple versions of python installed. In many installations, pip is for python 2.7 and pip3 if for python 3.x. As a quick test, try pip3 for your command.

**Comment by guiamuchastegui** [comment]
I tried to use pip3, although it says pip3 it is not a known command.

**Comment by guiamuchastegui** [comment]
Any other idea on how to install vibrationtesting?

**Comment by josephcslater** [comment]
It's installed, but I think you have two different installations going on. Try the following. If this works, you have a version of pip pointing to a different python distribution:

```
python -m pip install --user vibrationtesting
```
If `python` isn't your command line call, use the appropriate call (perhaps `python3`). 

This will ensure that it is being installed where you want it installed.

**Comment by josephcslater** [comment]
Success? Can I close this?

**Comment by guiamuchastegui** [comment]
Joseph,
I didn't fix the problem, although its s a problem in my installation. I am looking for some solution, or I will have to reinstall Python.

**Comment by josephcslater** [comment]
I think that's the case. It's not difficult to muck around installing too much and clutter things up if you know too much. In my observation, installing anaconda python simplifies the whole thing.

**Comment by josephcslater** [comment]
I'm going to close this as resolved- not an issue of this module.
